-- Generated by web/scripts/gen-seed.ts from the demo's mock data. Do not edit; change the mock data and re-run.
-- Dev databases only: every person here is a made-up seed user (seed+…@pikyoo.test) and the photos are demo stock photos.

-- the token columns are '' rather than null because Supabase Auth can't read null there
insert into auth.users (id, aud, role, email, confirmation_token, recovery_token, email_change_token_new, email_change, raw_user_meta_data) values
  (md5('pikyoo-seed:Mia 林')::uuid, 'authenticated', 'authenticated', 'seed+1@pikyoo.test', '', '', '', '', '{"name":"Mia 林"}'::jsonb),
  (md5('pikyoo-seed:趙柏宇')::uuid, 'authenticated', 'authenticated', 'seed+2@pikyoo.test', '', '', '', '', '{"name":"趙柏宇"}'::jsonb),
  (md5('pikyoo-seed:安妮')::uuid, 'authenticated', 'authenticated', 'seed+3@pikyoo.test', '', '', '', '', '{"name":"安妮"}'::jsonb),
  (md5('pikyoo-seed:Ray 陳')::uuid, 'authenticated', 'authenticated', 'seed+4@pikyoo.test', '', '', '', '', '{"name":"Ray 陳"}'::jsonb),
  (md5('pikyoo-seed:阿凱')::uuid, 'authenticated', 'authenticated', 'seed+5@pikyoo.test', '', '', '', '', '{"name":"阿凱"}'::jsonb),
  (md5('pikyoo-seed:林小姐')::uuid, 'authenticated', 'authenticated', 'seed+6@pikyoo.test', '', '', '', '', '{"name":"林小姐"}'::jsonb),
  (md5('pikyoo-seed:安安')::uuid, 'authenticated', 'authenticated', 'seed+7@pikyoo.test', '', '', '', '', '{"name":"安安"}'::jsonb),
  (md5('pikyoo-seed:Mandy')::uuid, 'authenticated', 'authenticated', 'seed+8@pikyoo.test', '', '', '', '', '{"name":"Mandy"}'::jsonb),
  (md5('pikyoo-seed:吳大哥')::uuid, 'authenticated', 'authenticated', 'seed+9@pikyoo.test', '', '', '', '', '{"name":"吳大哥"}'::jsonb),
  (md5('pikyoo-seed:陳 Ray')::uuid, 'authenticated', 'authenticated', 'seed+10@pikyoo.test', '', '', '', '', '{"name":"陳 Ray"}'::jsonb),
  (md5('pikyoo-seed:小芸')::uuid, 'authenticated', 'authenticated', 'seed+11@pikyoo.test', '', '', '', '', '{"name":"小芸"}'::jsonb),
  (md5('pikyoo-seed:許許')::uuid, 'authenticated', 'authenticated', 'seed+12@pikyoo.test', '', '', '', '', '{"name":"許許"}'::jsonb),
  (md5('pikyoo-seed:小周')::uuid, 'authenticated', 'authenticated', 'seed+13@pikyoo.test', '', '', '', '', '{"name":"小周"}'::jsonb),
  (md5('pikyoo-seed:Peggy')::uuid, 'authenticated', 'authenticated', 'seed+14@pikyoo.test', '', '', '', '', '{"name":"Peggy"}'::jsonb),
  (md5('pikyoo-seed:豪哥')::uuid, 'authenticated', 'authenticated', 'seed+15@pikyoo.test', '', '', '', '', '{"name":"豪哥"}'::jsonb),
  (md5('pikyoo-seed:柏翰')::uuid, 'authenticated', 'authenticated', 'seed+16@pikyoo.test', '', '', '', '', '{"name":"柏翰"}'::jsonb),
  (md5('pikyoo-seed:宇恆')::uuid, 'authenticated', 'authenticated', 'seed+17@pikyoo.test', '', '', '', '', '{"name":"宇恆"}'::jsonb),
  (md5('pikyoo-seed:阿睿')::uuid, 'authenticated', 'authenticated', 'seed+18@pikyoo.test', '', '', '', '', '{"name":"阿睿"}'::jsonb),
  (md5('pikyoo-seed:葉子')::uuid, 'authenticated', 'authenticated', 'seed+19@pikyoo.test', '', '', '', '', '{"name":"葉子"}'::jsonb),
  (md5('pikyoo-seed:潘潘')::uuid, 'authenticated', 'authenticated', 'seed+20@pikyoo.test', '', '', '', '', '{"name":"潘潘"}'::jsonb),
  (md5('pikyoo-seed:蔡哥')::uuid, 'authenticated', 'authenticated', 'seed+21@pikyoo.test', '', '', '', '', '{"name":"蔡哥"}'::jsonb),
  (md5('pikyoo-seed:Jason')::uuid, 'authenticated', 'authenticated', 'seed+22@pikyoo.test', '', '', '', '', '{"name":"Jason"}'::jsonb),
  (md5('pikyoo-seed:阿何')::uuid, 'authenticated', 'authenticated', 'seed+23@pikyoo.test', '', '', '', '', '{"name":"阿何"}'::jsonb),
  (md5('pikyoo-seed:候補1')::uuid, 'authenticated', 'authenticated', 'seed+24@pikyoo.test', '', '', '', '', '{"name":"候補1"}'::jsonb),
  (md5('pikyoo-seed:候補2')::uuid, 'authenticated', 'authenticated', 'seed+25@pikyoo.test', '', '', '', '', '{"name":"候補2"}'::jsonb),
  (md5('pikyoo-seed:Wendy')::uuid, 'authenticated', 'authenticated', 'seed+26@pikyoo.test', '', '', '', '', '{"name":"Wendy"}'::jsonb),
  (md5('pikyoo-seed:Emily')::uuid, 'authenticated', 'authenticated', 'seed+27@pikyoo.test', '', '', '', '', '{"name":"Emily"}'::jsonb),
  (md5('pikyoo-seed:Leo')::uuid, 'authenticated', 'authenticated', 'seed+28@pikyoo.test', '', '', '', '', '{"name":"Leo"}'::jsonb),
  (md5('pikyoo-seed:小安')::uuid, 'authenticated', 'authenticated', 'seed+29@pikyoo.test', '', '', '', '', '{"name":"小安"}'::jsonb);

insert into public.courts (slug, name, city, district, address, kind, court_count, surface, is_free, price_note, hours_note,
  amenities, has_aircon, has_lights, booking_method, booking_note, rules, photos, verified_at) values (
  'daan', '大安運動中心', '台北市', '大安區', '台北市大安區辛亥路三段 55 號', 'indoor', 4, 'PU 多功能球場',
  false, '每面每小時約 NT$400（依時段）', '每天 06:00–22:00', array['冷氣', '淋浴', '停車', '租拍']::text[], true, true, 'public_system', '運動中心官網線上預約，開放 14 天內的時段',
  '需穿室內運動鞋；每次預約最多 2 小時。', '[{"path":"/photos/court-daan.jpg","alt":"空無一人的室內 PU 球場，藍色地板與白線"}]'::jsonb, '2026-09-01');
insert into public.courts (slug, name, city, district, address, kind, court_count, surface, is_free, price_note, hours_note,
  amenities, has_aircon, has_lights, booking_method, booking_note, rules, photos, verified_at) values (
  'xinyi', '信義運動中心', '台北市', '信義區', '台北市信義區松勤街 100 號', 'indoor', 3, 'PU 多功能球場',
  false, '每面每小時約 NT$450（依時段）', '每天 06:00–22:00', array['冷氣', '淋浴', '停車']::text[], true, true, 'public_system', '運動中心官網線上預約',
  '需穿室內運動鞋。', '[{"path":"/photos/court-xinyi.jpg","alt":"室內球場上兩位球員在對打"}]'::jsonb, '2026-09-01');
insert into public.courts (slug, name, city, district, address, kind, court_count, surface, is_free, price_note, hours_note,
  amenities, has_aircon, has_lights, booking_method, booking_note, rules, photos, verified_at) values (
  'dajia', '大佳河濱公園', '台北市', '中山區', '台北市中山區濱江街 5 號', 'outdoor', 6, '硬地',
  true, '免費', '全天開放・夜間照明到 22:00', array['夜間照明', '停車']::text[], false, true, 'walk_in', '先到先打，週末早上人多',
  '下雨地滑請勿使用；請自備球網以外的器材。', '[{"path":"/photos/court-dajia.jpg","alt":"綠樹環繞、有圍網的戶外球場"}]'::jsonb, '2026-09-01');
insert into public.courts (slug, name, city, district, address, kind, court_count, surface, is_free, price_note, hours_note,
  amenities, has_aircon, has_lights, booking_method, booking_note, rules, photos, verified_at) values (
  'zhongshan', '中山運動中心', '台北市', '中山區', '台北市中山區中山北路二段 44 巷 2 號', 'indoor', 4, 'PU 多功能球場',
  false, '每面每小時約 NT$400（依時段）', '每天 06:00–22:00', array['冷氣', '淋浴', '租拍']::text[], true, true, 'public_system', '運動中心官網線上預約',
  '需穿室內運動鞋。', '[{"path":"/photos/court-zhongshan.jpg","alt":"室內球場上女球員在網前擊球"}]'::jsonb, null);
insert into public.courts (slug, name, city, district, address, kind, court_count, surface, is_free, price_note, hours_note,
  amenities, has_aircon, has_lights, booking_method, booking_note, rules, photos, verified_at) values (
  'neihu', '內湖運動中心', '台北市', '內湖區', '台北市內湖區洲子街 12 號', 'indoor', 3, 'PU 多功能球場',
  false, '每面每小時約 NT$350（依時段）', '每天 06:00–22:00', array['冷氣', '停車']::text[], true, true, 'public_system', '運動中心官網線上預約',
  '需穿室內運動鞋。', '[{"path":"/photos/court-neihu.jpg","alt":"室內球場上男球員準備擊球"}]'::jsonb, null);
insert into public.courts (slug, name, city, district, address, kind, court_count, surface, is_free, price_note, hours_note,
  amenities, has_aircon, has_lights, booking_method, booking_note, rules, photos, verified_at) values (
  'banqiao', '新北市板橋第一運動場風雨球場', '新北市', '板橋區', '新北市板橋區漢生東路 278 號', 'covered', 2, '硬地',
  false, '每小時約 NT$200', '每天 06:00–22:00', array['夜間照明', '停車']::text[], false, true, 'phone', '打電話到場館管理室預約',
  '颱風與豪雨停開。', '[{"path":"/photos/court-banqiao.jpg","alt":"夜間打燈的兩面球場空拍"}]'::jsonb, null);
insert into public.coaches (profile_id, slug, name, status, tagline, bio, areas, level_min, level_max, style, beginner_friendly,
  coaching_since, reply_note, play, audience, languages, availability, venues, steps, pay_methods, policy, photos, timeline, quotes, approved_at) values (
  md5('pikyoo-seed:Mia 林')::uuid, 'mia', 'Mia 林', 'approved', '網球教練 8 年轉匹克球，專帶第一次拿拍的人。', '我相信第一堂課最重要的是「打得到球、想再來」。每堂課會拍一段你的揮拍影片，課後用 LINE 傳給你，附上一個回家可以練的重點。', array['大安', '信義']::text[], 0, 3, array['新手友善', '拆解動作', '影片回饋']::text[],
  true, 2023, '通常 2 小時內回覆', '{"since":"2022","hand":"右手","format":"雙打為主","background":"網球教練 8 年","strengths":["零基礎入門","發球與接發球","網前小球（dink）","網球轉匹克球的揮拍修正"]}'::jsonb, array['第一次拿拍', '打過網球、羽球想轉項', '想先上課再去打新手局', '跟朋友一起來的小班']::text[], array['中文', '英文']::text[], '{"二":["19:30"],"三":["19:30"],"五":["20:00"],"六":["09:00","14:00"],"日":["10:00","15:00"]}'::jsonb,
  '[{"name":"大安運動中心","sub":"室內 4 面・大安區","court_slug":"daan"},{"name":"信義運動中心","sub":"室內 3 面・信義區","court_slug":"xinyi"}]'::jsonb, array['握拍與準備姿勢，先把球打過網', '分解動作＋當場錄影給你看', '小比賽實戰，課後 LINE 傳影片與功課']::text[],
  array['line_pay', 'bank_transfer', 'cash']::public.pay_method[], '上課前 24 小時可免費改期或取消；24 小時內取消收 50%。',
  '[{"path":"/photos/mia-cover.jpg","alt":"女教練拿著球拍在室內球場準備接球","caption":"大安運動中心"},{"path":"/photos/mia-lesson.jpg","alt":"女教練在室內球場拿著球拍和球準備發球","caption":"第一堂課：握拍與準備姿勢"},{"path":"/photos/mia-group.jpg","alt":"兩位學員在室內球場對打練習","caption":"小班課：網前小球"}]'::jsonb, '[{"year":"2026","text":"中華民國匹克球協會 認證教練","kind":"cert"},{"year":"2025","text":"TMLP 台北站 女子雙打 第 5 名","kind":"trophy"},{"year":"2024","text":"開始教匹克球，累計 128 位學生","kind":"users"},{"year":"2016–24","text":"網球教練（8 年）","kind":"cap"}]'::jsonb, '[{"name":"小芸","level":"新手 → 2.5","text":"第一堂就能對打十拍，影片回饋超有用。"},{"name":"Jason","level":"2.5","text":"把我網球的揮拍習慣一個一個拆掉，很有耐心。"}]'::jsonb, now());
insert into public.credentials (coach_id, type, issuer, level, status) values ((select id from public.coaches where slug = 'mia'), 'coach_cert', '協會', '認證教練', 'verified');
insert into public.credentials (coach_id, type, issuer, level, status) values ((select id from public.coaches where slug = 'mia'), 'dupr', 'DUPR', '4.21', 'self_reported');
insert into public.coach_plans (coach_id, key, name, kind, duration_min, size_label, capacity, group_min, group_max, price, unit, note, tag, sort) values (
  (select id from public.coaches where slug = 'mia'), 'trial', '新手體驗課', 'trial', 60, '2–4 人', 4,
  2, 4, 600, 'per_person', '含借拍與球・第一次打也 OK', '最多人選', 0);
insert into public.coach_plans (coach_id, key, name, kind, duration_min, size_label, capacity, group_min, group_max, price, unit, note, tag, sort) values (
  (select id from public.coaches where slug = 'mia'), 'p1', '一對一', 'private', 60, '1 人', 1,
  null, null, 1500, 'per_lesson', '場地費另計（約 NT$200，教練代訂）', null, 1);
insert into public.coach_plans (coach_id, key, name, kind, duration_min, size_label, capacity, group_min, group_max, price, unit, note, tag, sort) values (
  (select id from public.coaches where slug = 'mia'), 'small', '小班課', 'small', 90, '3–4 人', 4,
  3, 4, 800, 'per_person', '同程度分組，可自組朋友班', null, 2);
insert into public.coach_plans (coach_id, key, name, kind, duration_min, size_label, capacity, group_min, group_max, price, unit, note, tag, sort) values (
  (select id from public.coaches where slug = 'mia'), 'pack', '一對一 10 堂', 'private', 60, '1 人', 1,
  null, null, 13500, 'per_pack', '每堂 NT$1,350・6 個月內用完', '省 NT$1,500', 3);
insert into public.coaches (profile_id, slug, name, status, tagline, bio, areas, level_min, level_max, style, beginner_friendly,
  coaching_since, reply_note, play, audience, languages, availability, venues, steps, pay_methods, policy, photos, timeline, quotes, approved_at) values (
  md5('pikyoo-seed:趙柏宇')::uuid, 'zhao', '趙柏宇', 'approved', 'TMLP 台北站雙打銅牌，把 3.0 打到 3.5。', '很多人卡在 3.0，是因為第三拍和網前轉換沒有固定打法。我會先看你打一局，找出最常失分的兩個球，接下來每堂課只練那兩個，直到比賽裡用得出來。', array['信義', '松山']::text[], 2, 5, array['比賽策略', '第三拍', '雙打站位']::text[],
  false, 2022, '通常當天回覆', '{"since":"2020","hand":"右手","format":"雙打為主","background":"桌球校隊、羽球 10 年","strengths":["第三拍 drop","重置球（reset）","雙打站位與換位","比賽策略"]}'::jsonb, array['2.5–3.0 想升級', '準備參加積分賽', '固定球友想一起練戰術']::text[], array['中文']::text[], '{"二":["20:00"],"四":["19:30","21:00"],"六":["16:00"],"日":["09:00"]}'::jsonb,
  '[{"name":"信義運動中心","sub":"室內 3 面・信義區","court_slug":"xinyi"},{"name":"松山運動中心","sub":"室內・松山區","court_slug":null}]'::jsonb, array['先打一局，找出最常失分的兩個球', '每堂只練那兩個球，拆解到你能重複', '2 對 2 實戰，比賽裡用出來才算數']::text[],
  array['bank_transfer', 'cash']::public.pay_method[], '上課前 48 小時可免費改期；48 小時內取消收全額。',
  '[{"path":"/photos/zhao-cover.jpg","alt":"男教練在室內球場網前低手救球","caption":"信義運動中心"},{"path":"/photos/zhao-lesson.jpg","alt":"雙打練習中，球員在網前壓低準備截擊","caption":"雙打站位與換位"},{"path":"/photos/zhao-match.jpg","alt":"室內比賽場館裡的雙打比賽","caption":"帶學生參加積分賽"}]'::jsonb, '[{"year":"2026","text":"中華民國匹克球總會 丙級教練","kind":"cert"},{"year":"2025","text":"PPR Certified Coach","kind":"cert"},{"year":"2025","text":"TMLP 台北站 男子雙打 第 3 名","kind":"trophy"},{"year":"2022","text":"開始教匹克球，累計 86 位學生","kind":"users"}]'::jsonb, '[{"name":"阿睿","level":"3.0 → 3.5","text":"第三拍終於不再亂打，積分賽第一次打進八強。"},{"name":"Peggy","level":"3.0","text":"講解很有邏輯，每次都知道下一步要練什麼。"}]'::jsonb, now());
insert into public.credentials (coach_id, type, issuer, level, status) values ((select id from public.coaches where slug = 'zhao'), 'coach_cert', '總會', '丙級教練', 'verified');
insert into public.credentials (coach_id, type, issuer, level, status) values ((select id from public.coaches where slug = 'zhao'), 'coach_cert', 'PPR', 'Certified', 'verified');
insert into public.coach_plans (coach_id, key, name, kind, duration_min, size_label, capacity, group_min, group_max, price, unit, note, tag, sort) values (
  (select id from public.coaches where slug = 'zhao'), 'p1', '一對一', 'private', 60, '1 人', 1,
  null, null, 1200, 'per_lesson', '先打一局評估，再排練習重點', null, 0);
insert into public.coach_plans (coach_id, key, name, kind, duration_min, size_label, capacity, group_min, group_max, price, unit, note, tag, sort) values (
  (select id from public.coaches where slug = 'zhao'), 'small', '戰術小班', 'small', 90, '3–4 人', 4,
  3, 4, 900, 'per_person', '同程度 2 對 2 實戰＋暫停講解', null, 1);
insert into public.coach_plans (coach_id, key, name, kind, duration_min, size_label, capacity, group_min, group_max, price, unit, note, tag, sort) values (
  (select id from public.coaches where slug = 'zhao'), 'pack', '一對一 10 堂', 'private', 60, '1 人', 1,
  null, null, 11000, 'per_pack', '每堂 NT$1,100・4 個月內用完', '省 NT$1,000', 2);
insert into public.coaches (profile_id, slug, name, status, tagline, bio, areas, level_min, level_max, style, beginner_friendly,
  coaching_since, reply_note, play, audience, languages, availability, venues, steps, pay_methods, policy, photos, timeline, quotes, approved_at) values (
  md5('pikyoo-seed:安妮')::uuid, 'ann', '安妮', 'approved', '週末團體課，一個人來也能馬上找到球伴。', '團體課的好處是：你會認識一群程度差不多的球友。我的課前半小時練基本動作，後面一小時分組打比賽，下課前大家常常就約好下一次一起打了。', array['中山', '大同']::text[], 0, 2, array['團體課', '親子', '可英文授課']::text[],
  true, 2024, '通常 1 小時內回覆', '{"since":"2022","hand":"右手","format":"雙打為主","background":"兒童體適能教練 5 年","strengths":["零基礎入門","團體分組練習","發球與接發球","親子課"]}'::jsonb, array['一個人想找球伴', '第一次拿拍', '親子一起學', '英文授課需求']::text[], array['中文', '英文']::text[], '{"三":["19:00"],"六":["09:00","14:00"],"日":["09:00"]}'::jsonb,
  '[{"name":"中山運動中心","sub":"室內 4 面・中山區","court_slug":"zhongshan"},{"name":"大佳河濱公園","sub":"室外 6 面・中山區","court_slug":"dajia"}]'::jsonb, array['30 分鐘基本動作：握拍、發球、接發', '分組輪轉，每個人都有很多擊球機會', '小比賽＋認識球友，下課一起約下次']::text[],
  array['line_pay', 'cash']::public.pay_method[], '上課前 24 小時可免費取消；雨天室外課改到室內或延期。',
  '[{"path":"/photos/ann-cover.jpg","alt":"女教練在室內球場網前準備接球","caption":"中山運動中心"},{"path":"/photos/ann-group.jpg","alt":"週末團體課學員在戶外球場分組打雙打","caption":"週末團體課：分組比賽"},{"path":"/photos/ann-gear.jpg","alt":"球網前放著兩支球拍和幾顆洞洞球","caption":"借拍與球都準備好了"}]'::jsonb, '[{"year":"2025","text":"IPTPA Level 1 認證","kind":"cert"},{"year":"2024","text":"開始帶週末團體課，累計 210 位學生","kind":"users"},{"year":"2019–24","text":"兒童體適能教練（5 年）","kind":"cap"}]'::jsonb, '[{"name":"葉子","level":"新手","text":"一個人去完全不尷尬，下課就加了三個球友。"},{"name":"Emily","level":"2.0","text":"Classes in English were really helpful for me."}]'::jsonb, now());
insert into public.credentials (coach_id, type, issuer, level, status) values ((select id from public.coaches where slug = 'ann'), 'coach_cert', 'IPTPA', 'Level 1', 'verified');
insert into public.coach_plans (coach_id, key, name, kind, duration_min, size_label, capacity, group_min, group_max, price, unit, note, tag, sort) values (
  (select id from public.coaches where slug = 'ann'), 'trial', '團體體驗課', 'trial', 90, '4–8 人', 8,
  2, 8, 450, 'per_person', '含借拍與球・一個人報名也可以', '新手首選', 0);
insert into public.coach_plans (coach_id, key, name, kind, duration_min, size_label, capacity, group_min, group_max, price, unit, note, tag, sort) values (
  (select id from public.coaches where slug = 'ann'), 'group', '週末團體課', 'group', 90, '6–8 人', 8,
  4, 8, 400, 'per_person', '前 30 分鐘基本動作，後 60 分鐘分組比賽', null, 1);
insert into public.coach_plans (coach_id, key, name, kind, duration_min, size_label, capacity, group_min, group_max, price, unit, note, tag, sort) values (
  (select id from public.coaches where slug = 'ann'), 'family', '親子課', 'private', 60, '1 大 1 小', 1,
  null, null, 900, 'per_lesson', '小朋友 7 歲以上', null, 2);
insert into public.coaches (profile_id, slug, name, status, tagline, bio, areas, level_min, level_max, style, beginner_friendly,
  coaching_since, reply_note, play, audience, languages, availability, venues, steps, pay_methods, policy, photos, timeline, quotes, approved_at) values (
  md5('pikyoo-seed:Ray 陳')::uuid, 'ray', 'Ray 陳', 'approved', '4.5 以上陪練，備戰積分賽。', '我自己還在打 DUPR 積分賽，所以課程就是比賽節奏：高強度對抽、發球變化、單打跑位。適合已經會打、想找強度的人。', array['內湖', '南港']::text[], 3, 6, array['進階陪練', '比賽準備']::text[],
  false, 2025, '通常當天回覆', '{"since":"2019","hand":"左手","format":"單打、雙打都教","background":"網球選手出身","strengths":["快速對抽（hands battle）","發球變化","單打戰術","比賽心理"]}'::jsonb, array['3.5 以上想找強度', '備戰 DUPR 積分賽', '想練單打']::text[], array['中文', '英文']::text[], '{"一":["20:00"],"三":["19:00"],"五":["20:00"],"日":["15:00"]}'::jsonb,
  '[{"name":"內湖運動中心","sub":"室內 3 面・內湖區","court_slug":"neihu"}]'::jsonb, array['暖身後直接比賽強度對抽', '針對弱點設計情境練習', '模擬積分賽的一局，檢討每一分']::text[],
  array['bank_transfer', 'line_pay']::public.pay_method[], '上課前 24 小時可免費改期。',
  '[{"path":"/photos/ray-cover.jpg","alt":"男球員左手持拍在室內球場網前擊球","caption":"內湖運動中心"},{"path":"/photos/ray-match.jpg","alt":"室內比賽場館裡的雙打比賽","caption":"陪學生備戰積分賽"}]'::jsonb, '[{"year":"2026","text":"DUPR 4.65（自填，待驗證）","kind":"trophy"},{"year":"2025","text":"開始陪練教學，累計 24 位學生","kind":"users"},{"year":"2012–18","text":"網球選手（高中、大專盃）","kind":"cap"}]'::jsonb, '[]'::jsonb, now());
insert into public.credentials (coach_id, type, issuer, level, status) values ((select id from public.coaches where slug = 'ray'), 'dupr', 'DUPR', '4.65', 'self_reported');
insert into public.coach_plans (coach_id, key, name, kind, duration_min, size_label, capacity, group_min, group_max, price, unit, note, tag, sort) values (
  (select id from public.coaches where slug = 'ray'), 'p1', '一對一陪練', 'private', 60, '1 人', 1,
  null, null, 1500, 'per_lesson', '比賽強度，需有 3.5 以上程度', null, 0);
insert into public.coach_plans (coach_id, key, name, kind, duration_min, size_label, capacity, group_min, group_max, price, unit, note, tag, sort) values (
  (select id from public.coaches where slug = 'ray'), 'duo', '兩人陪練', 'small', 90, '2 人', 2,
  2, 2, 1000, 'per_person', '帶一位球友一起來，練雙打配合', null, 1);
insert into public.games (id, host_id, court_id, location_text, address, district, starts_at, ends_at, level_min, level_max, capacity,
  fee, fee_note, cancel_hours, beginner_friendly, notes) values (
  md5('pikyoo-seed-game:g1')::uuid, md5('pikyoo-seed:阿凱')::uuid, (select id from public.courts where slug = 'daan'), '', '台北市大安區辛亥路三段 55 號', '大安區',
  ((date_trunc('day', now() at time zone 'Asia/Taipei') + interval '0 days' + time '19:00') at time zone 'Asia/Taipei'), ((date_trunc('day', now() at time zone 'Asia/Taipei') + interval '0 days' + time '21:00') at time zone 'Asia/Taipei'), 2, 3, 8, 150, '現場付現給團主', 12,
  false, '球由團主準備，現場有 2 支拍可借。打輪轉，一場 11 分。');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g1')::uuid, md5('pikyoo-seed:林小姐')::uuid, md5('pikyoo-seed:林小姐')::uuid, 'joined', now() - interval '5 hours');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g1')::uuid, md5('pikyoo-seed:安安')::uuid, md5('pikyoo-seed:安安')::uuid, 'joined', now() - interval '4 hours');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g1')::uuid, md5('pikyoo-seed:Mandy')::uuid, md5('pikyoo-seed:Mandy')::uuid, 'joined', now() - interval '3 hours');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g1')::uuid, md5('pikyoo-seed:吳大哥')::uuid, md5('pikyoo-seed:吳大哥')::uuid, 'joined', now() - interval '2 hours');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g1')::uuid, md5('pikyoo-seed:陳 Ray')::uuid, md5('pikyoo-seed:陳 Ray')::uuid, 'joined', now() - interval '1 hours');
insert into public.games (id, host_id, court_id, location_text, address, district, starts_at, ends_at, level_min, level_max, capacity,
  fee, fee_note, cancel_hours, beginner_friendly, notes) values (
  md5('pikyoo-seed-game:g2')::uuid, md5('pikyoo-seed:小芸')::uuid, (select id from public.courts where slug = 'xinyi'), '', '台北市信義區松勤街 100 號', '信義區',
  ((date_trunc('day', now() at time zone 'Asia/Taipei') + interval '0 days' + time '20:00') at time zone 'Asia/Taipei'), ((date_trunc('day', now() at time zone 'Asia/Taipei') + interval '0 days' + time '22:00') at time zone 'Asia/Taipei'), 0, 2, 8, 200, '轉帳或現場付現', 12,
  true, '第一次打也可以來！前 20 分鐘會先帶規則和發球。');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g2')::uuid, md5('pikyoo-seed:許許')::uuid, md5('pikyoo-seed:許許')::uuid, 'joined', now() - interval '4 hours');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g2')::uuid, md5('pikyoo-seed:小周')::uuid, md5('pikyoo-seed:小周')::uuid, 'joined', now() - interval '3 hours');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g2')::uuid, md5('pikyoo-seed:林小姐')::uuid, md5('pikyoo-seed:林小姐')::uuid, 'joined', now() - interval '2 hours');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g2')::uuid, md5('pikyoo-seed:Peggy')::uuid, md5('pikyoo-seed:Peggy')::uuid, 'joined', now() - interval '1 hours');
insert into public.games (id, host_id, court_id, location_text, address, district, starts_at, ends_at, level_min, level_max, capacity,
  fee, fee_note, cancel_hours, beginner_friendly, notes) values (
  md5('pikyoo-seed-game:g3')::uuid, md5('pikyoo-seed:豪哥')::uuid, (select id from public.courts where slug = 'dajia'), '', '台北市中山區濱江街 5 號', '中山區',
  ((date_trunc('day', now() at time zone 'Asia/Taipei') + interval '1 days' + time '07:00') at time zone 'Asia/Taipei'), ((date_trunc('day', now() at time zone 'Asia/Taipei') + interval '1 days' + time '09:00') at time zone 'Asia/Taipei'), 3, 4, 4, 50, '現場付現', 12,
  false, '下雨取消，前一晚 22:00 在群組通知。');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g3')::uuid, md5('pikyoo-seed:柏翰')::uuid, md5('pikyoo-seed:柏翰')::uuid, 'joined', now() - interval '2 hours');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g3')::uuid, md5('pikyoo-seed:宇恆')::uuid, md5('pikyoo-seed:宇恆')::uuid, 'joined', now() - interval '1 hours');
insert into public.games (id, host_id, court_id, location_text, address, district, starts_at, ends_at, level_min, level_max, capacity,
  fee, fee_note, cancel_hours, beginner_friendly, notes) values (
  md5('pikyoo-seed-game:g4')::uuid, md5('pikyoo-seed:小芸')::uuid, (select id from public.courts where slug = 'banqiao'), '', '新北市板橋區漢生東路 278 號', '板橋區',
  ((date_trunc('day', now() at time zone 'Asia/Taipei') + interval '4 days' + time '14:00') at time zone 'Asia/Taipei'), ((date_trunc('day', now() at time zone 'Asia/Taipei') + interval '4 days' + time '16:00') at time zone 'Asia/Taipei'), 0, 2, 6, 180, '現場付現', 12,
  true, '新手團，會分程度輪轉。');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g4')::uuid, md5('pikyoo-seed:許許')::uuid, md5('pikyoo-seed:許許')::uuid, 'joined', now() - interval '2 hours');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g4')::uuid, md5('pikyoo-seed:小周')::uuid, md5('pikyoo-seed:小周')::uuid, 'joined', now() - interval '1 hours');
insert into public.games (id, host_id, court_id, location_text, address, district, starts_at, ends_at, level_min, level_max, capacity,
  fee, fee_note, cancel_hours, beginner_friendly, notes) values (
  md5('pikyoo-seed-game:g5')::uuid, md5('pikyoo-seed:阿睿')::uuid, (select id from public.courts where slug = 'neihu'), '', '台北市內湖區洲子街 12 號', '內湖區',
  ((date_trunc('day', now() at time zone 'Asia/Taipei') + interval '4 days' + time '19:00') at time zone 'Asia/Taipei'), ((date_trunc('day', now() at time zone 'Asia/Taipei') + interval '4 days' + time '21:30') at time zone 'Asia/Taipei'), 4, 5, 6, 250, '轉帳（報名後團主提供帳號）', 12,
  false, '比賽節奏，請準時到場熱身。');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g5')::uuid, md5('pikyoo-seed:葉子')::uuid, md5('pikyoo-seed:葉子')::uuid, 'joined', now() - interval '7 hours');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g5')::uuid, md5('pikyoo-seed:潘潘')::uuid, md5('pikyoo-seed:潘潘')::uuid, 'joined', now() - interval '6 hours');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g5')::uuid, md5('pikyoo-seed:蔡哥')::uuid, md5('pikyoo-seed:蔡哥')::uuid, 'joined', now() - interval '5 hours');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g5')::uuid, md5('pikyoo-seed:Jason')::uuid, md5('pikyoo-seed:Jason')::uuid, 'joined', now() - interval '4 hours');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g5')::uuid, md5('pikyoo-seed:阿何')::uuid, md5('pikyoo-seed:阿何')::uuid, 'joined', now() - interval '3 hours');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g5')::uuid, md5('pikyoo-seed:候補1')::uuid, md5('pikyoo-seed:候補1')::uuid, 'waitlisted', now() - interval '2 hours');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g5')::uuid, md5('pikyoo-seed:候補2')::uuid, md5('pikyoo-seed:候補2')::uuid, 'waitlisted', now() - interval '1 hours');
insert into public.games (id, host_id, court_id, location_text, address, district, starts_at, ends_at, level_min, level_max, capacity,
  fee, fee_note, cancel_hours, beginner_friendly, notes) values (
  md5('pikyoo-seed-game:g6')::uuid, md5('pikyoo-seed:阿凱')::uuid, (select id from public.courts where slug = 'zhongshan'), '', '台北市中山區中山北路二段 44 巷 2 號', '中山區',
  ((date_trunc('day', now() at time zone 'Asia/Taipei') + interval '5 days' + time '10:00') at time zone 'Asia/Taipei'), ((date_trunc('day', now() at time zone 'Asia/Taipei') + interval '5 days' + time '12:00') at time zone 'Asia/Taipei'), 1, 3, 8, 150, '現場付現給團主', 12,
  true, '週日早場，打完一起吃早午餐。');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g6')::uuid, md5('pikyoo-seed:Mandy')::uuid, md5('pikyoo-seed:Mandy')::uuid, 'joined', now() - interval '3 hours');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g6')::uuid, md5('pikyoo-seed:吳大哥')::uuid, md5('pikyoo-seed:吳大哥')::uuid, 'joined', now() - interval '2 hours');
insert into public.game_participants (game_id, user_id, added_by, status, joined_at) values (md5('pikyoo-seed-game:g6')::uuid, md5('pikyoo-seed:安安')::uuid, md5('pikyoo-seed:安安')::uuid, 'joined', now() - interval '1 hours');
insert into public.questions (coach_id, asker_id, text, answer, answered_at, created_at) values ((select id from public.coaches where slug = 'mia'), md5('pikyoo-seed:小芸')::uuid, '完全沒打過球，也沒有球拍，可以直接報體驗課嗎？',
  '可以！體驗課會借你球拍和球，穿運動鞋來就好。第一堂從握拍開始，下課前一定能對打。', timestamptz '2026-9-12 12:00+08', timestamptz '2026-9-12 12:00+08');
insert into public.questions (coach_id, asker_id, text, answer, answered_at, created_at) values ((select id from public.coaches where slug = 'mia'), md5('pikyoo-seed:Jason')::uuid, '打網球很多年，揮拍習慣會不會很難改？適合上一對一還是小班？',
  '網球底子其實是優勢，主要是改揮拍幅度和網前的手腕。建議先上 1–2 堂一對一把習慣拆掉，再來小班練實戰。', timestamptz '2026-9-18 12:00+08', timestamptz '2026-9-18 12:00+08');
insert into public.questions (coach_id, asker_id, text, answer, answered_at, created_at) values ((select id from public.coaches where slug = 'mia'), md5('pikyoo-seed:阿凱')::uuid, '兩個人可以一起報小班課嗎？還是要湊滿 3 個人？',
  '小班最少 3 人。兩個人的話可以用「揪朋友一起上」先佔時段，再找一位朋友，或是改上體驗課（2 人就開）。', timestamptz '2026-9-25 12:00+08', timestamptz '2026-9-25 12:00+08');
insert into public.questions (coach_id, asker_id, text, answer, answered_at, created_at) values ((select id from public.coaches where slug = 'mia'), md5('pikyoo-seed:Wendy')::uuid, '週末早上 9 點的課，遇到下雨會停課嗎？',
  null, null, now());
insert into public.questions (coach_id, asker_id, text, answer, answered_at, created_at) values ((select id from public.coaches where slug = 'zhao'), md5('pikyoo-seed:Peggy')::uuid, '我是 3.0，第三拍常常掛網，一對一大概要上幾堂才會有感？',
  '通常 3–4 堂會有感。第一堂我會先看你打一局，確定是準備太慢還是拍面角度，之後每堂只練那個。', timestamptz '2026-9-20 12:00+08', timestamptz '2026-9-20 12:00+08');
insert into public.questions (coach_id, asker_id, text, answer, answered_at, created_at) values ((select id from public.coaches where slug = 'zhao'), md5('pikyoo-seed:阿睿')::uuid, '戰術小班可以自己組同一隊的 4 個人嗎？',
  '可以，用「揪朋友一起上」開團，4 個人都加入後送給我確認。固定隊友一起練雙打換位效果最好。', timestamptz '2026-9-27 12:00+08', timestamptz '2026-9-27 12:00+08');
insert into public.questions (coach_id, asker_id, text, answer, answered_at, created_at) values ((select id from public.coaches where slug = 'ann'), md5('pikyoo-seed:葉子')::uuid, '一個人報團體課會不會很尷尬？',
  '完全不會，大部分人都是一個人來的！我會依程度分組輪轉，下課大家常常就約下一次一起打了。', timestamptz '2026-9-15 12:00+08', timestamptz '2026-9-15 12:00+08');
insert into public.questions (coach_id, asker_id, text, answer, answered_at, created_at) values ((select id from public.coaches where slug = 'ann'), md5('pikyoo-seed:Emily')::uuid, 'Is the weekend class taught in English?',
  'Yes! I teach in both Chinese and English. Just mention it in the booking note.', timestamptz '2026-9-22 12:00+08', timestamptz '2026-9-22 12:00+08');
insert into public.questions (coach_id, asker_id, text, answer, answered_at, created_at) values ((select id from public.coaches where slug = 'ray'), md5('pikyoo-seed:Leo')::uuid, '我 DUPR 3.6，跟得上陪練的強度嗎？',
  '3.5 以上就可以。第一堂我會先用中等強度對抽，看你的狀況再往上加。', timestamptz '2026-9-26 12:00+08', timestamptz '2026-9-26 12:00+08');
insert into public.lesson_bookings (coach_id, plan_id, student_id, starts_at, headcount, note, pay_method, amount, expires_at) values (
  (select id from public.coaches where slug = 'mia'), (select id from public.coach_plans where coach_id = (select id from public.coaches where slug = 'mia') and key = 'trial'), md5('pikyoo-seed:小安')::uuid, ((date_trunc('day', now() at time zone 'Asia/Taipei') + interval '5 days' + time '10:00') at time zone 'Asia/Taipei'), 1, '第一次打，之前打過羽球。', 'line_pay', 600, now() + interval '46 hours');
insert into public.lesson_bookings (coach_id, plan_id, student_id, starts_at, headcount, note, pay_method, amount, expires_at) values (
  (select id from public.coaches where slug = 'mia'), (select id from public.coach_plans where coach_id = (select id from public.coaches where slug = 'mia') and key = 'p1'), md5('pikyoo-seed:Jason')::uuid, ((date_trunc('day', now() at time zone 'Asia/Taipei') + interval '8 days' + time '19:30') at time zone 'Asia/Taipei'), 1, '想加強反手截擊', 'bank_transfer', 1500, now() + interval '31 hours');
insert into public.lesson_groups (id, coach_id, plan_id, starts_at, organizer_id, invite_code, note, deadline_at) values (
  md5('pikyoo-seed-group:grp1')::uuid, (select id from public.coaches where slug = 'mia'), (select id from public.coach_plans where coach_id = (select id from public.coaches where slug = 'mia') and key = 'small'), ((date_trunc('day', now() at time zone 'Asia/Taipei') + interval '4 days' + time '14:00') at time zone 'Asia/Taipei'), md5('pikyoo-seed:小安')::uuid, 'seedgrp1', '同事三四個人，都是新手。', ((date_trunc('day', now() at time zone 'Asia/Taipei') + interval '4 days' + time '14:00') at time zone 'Asia/Taipei') - interval '24 hours');
insert into public.lesson_group_members (group_id, user_id) values (md5('pikyoo-seed-group:grp1')::uuid, md5('pikyoo-seed:小安')::uuid);
insert into public.lesson_group_members (group_id, user_id) values (md5('pikyoo-seed-group:grp1')::uuid, md5('pikyoo-seed:葉子')::uuid);
